In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers

from sklearn.model_selection import train_test_split

In [ ]:
np.random.seed(42)

n = 10000

df = pd.DataFrame({
    'soil_moisture': np.round(np.random.uniform(0.05, 0.85, n), 2),
    'temperature_c': np.round(np.random.uniform(15, 40, n), 1),
    'sunlight_hours': np.round(np.random.uniform(0, 12, n), 1)
})

df['needs_water'] = (
    (df['soil_moisture'] < 0.30) &
    (
        (df['temperature_c'] > 25) |
        (df['sunlight_hours'] > 7)
    )
).astype(int)

print(df.head())
print(df.shape)

   soil_moisture  temperature_c  sunlight_hours  needs_water
0           0.35           24.3             8.8            0
1           0.81           23.3             2.2            0
2           0.64           19.4             4.2            0
3           0.53           30.2             8.0            0
4           0.17           26.9             5.8            1
(10000, 4)

In [ ]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            0
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            1
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.20             22              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.10             20               1            1
15           0.30             29               9            1

In [ ]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [ ]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [ ]:
X_min = X.min()
X_max = X.max()
X_scaled = (X-X_min)/(X_max-X_min+1e-8)

In [ ]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.200000         0.1875        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.066667         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42,stratify=y)

In [ ]:
model = keras.Sequential([
    layers.Input(shape = (X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [ ]:
model.compile(
    loss = 'binary_crossentropy',
    optimizer = 'adam',
    metrics = ['accuracy']
)

In [ ]:
history = model.fit(
    X_train.values,
    y_train.values,
    validation_data=(X_test.values, y_test.values),
    epochs=10,
    batch_size=4,
    verbose=1
)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9299 - loss: 0.1499 - val_accuracy: 0.9224 - val_loss: 0.1721
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9268 - loss: 0.1508 - val_accuracy: 0.9372 - val_loss: 0.1387
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9279 - loss: 0.1502 - val_accuracy: 0.9400 - val_loss: 0.1380
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9280 - loss: 0.1491 - val_accuracy: 0.9408 - val_loss: 0.1379
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9281 - loss: 0.1485 - val_accuracy: 0.9288 - val_loss: 0.1543
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9281 - loss: 0.1481 - val_accuracy: 0.9356 - val_loss: 0.1440
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9276 - loss: 0.1498 - val_accuracy: 0.9384 - val_loss: 0.1373
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9283 - loss: 0.1478 - val_accuracy: 0.9360 - val_loss: 0.1399
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9275 - loss: 0.1485 - val_accuracy: 0.9356 - val_loss: 0.1392
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9299 - loss: 0.1476 - val_accuracy: 0.9388 - val_loss: 0.1378